### ISSUE TITLE
URGENT Le perso reste mort

### ISSUE THREAD

**Issue by Nono02P** [Sebajuste/davus_project#224]
Sur remise en place de sa vie maxi, le perso réapparait mort et ne sort jamais de cet état (dans le mode perlin et donjon).

**Comment by Nono02P** [comment]
Le problème est apparu depuis le commit suivant : 
https://github.com/Sebajuste/davus_project/commit/b7c0ad9c94d221dfe7be5b5f35dd5c449a843f44

**Comment by Sebajuste** [comment]
Corrigé. l'utilisation de find_node() renvoyé le CombatStats du bouclier ! (et non celui du personnage). Désormais il faut utiliser la méthode reset() du personnage
